version: 0.2

env:
  exported-variables:
    - CODEBUILD_BUILD_NUMBER

phases:
  install:
    commands:
      - node -v
      - npm install --global yarn
      - yarn

  build:
    commands:
      - npm run bundle:android
      - npm run bundle:ios

  post_build:
    commands:
      - "aws lambda invoke --function-name mfe-update-appconfig --region ap-southeast-1 --payload '{ \"targetModule\": \"reload\", \"version\": \"#{CODEBUILD_BUILD_NUMBER}\" }' response.json"

artifacts:
  files:
    - '**/*'
  base-directory: build/generated
