version: 0.2

env:
  exported-variables:
    - CODEBUILD_BUILD_NUMBER

phases:
  install:
    commands:
      - node -v
      - npm install --global yarn
      - yarn

  build:
    commands:
      - npm run bundle:android
      - npm run bundle:ios

  post_build:
    commands:
      - aws appconfig create-hosted-configuration-version --region us-east-1 --application-id pek2ts6 --configuration-profile-id ebiweto --content $CODEBUILD_BUILD_NUMBER --content-type "text/plain" configuration_version_output_file

artifacts:
  files:
    - '**/*'
  base-directory: build/generated
